# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:15:48+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Header, Path, Query
from pydantic import conint, constr
from starlette.requests import Request

from models import (
    AssignmentStatus,
    TaskReservationEnumStatus,
    TaskrouterV1Workspace,
    TaskrouterV1WorkspaceActivity,
    TaskrouterV1WorkspaceEvent,
    TaskrouterV1WorkspaceTask,
    TaskrouterV1WorkspaceTaskChannel,
    TaskrouterV1WorkspaceTaskQueue,
    TaskrouterV1WorkspaceTaskQueueTaskQueueCumulativeStatistics,
    TaskrouterV1WorkspaceTaskQueueTaskQueueRealTimeStatistics,
    TaskrouterV1WorkspaceTaskQueueTaskQueueStatistics,
    TaskrouterV1WorkspaceTaskTaskReservation,
    TaskrouterV1WorkspaceWorker,
    TaskrouterV1WorkspaceWorkerWorkerChannel,
    TaskrouterV1WorkspaceWorkerWorkerInstanceStatistics,
    TaskrouterV1WorkspaceWorkerWorkerReservation,
    TaskrouterV1WorkspaceWorkerWorkersCumulativeStatistics,
    TaskrouterV1WorkspaceWorkerWorkersRealTimeStatistics,
    TaskrouterV1WorkspaceWorkerWorkerStatistics,
    TaskrouterV1WorkspaceWorkflow,
    TaskrouterV1WorkspaceWorkflowWorkflowCumulativeStatistics,
    TaskrouterV1WorkspaceWorkflowWorkflowRealTimeStatistics,
    TaskrouterV1WorkspaceWorkflowWorkflowStatistics,
    TaskrouterV1WorkspaceWorkspaceCumulativeStatistics,
    TaskrouterV1WorkspaceWorkspaceRealTimeStatistics,
    TaskrouterV1WorkspaceWorkspaceStatistics,
    V1WorkspacesGetResponse,
    V1WorkspacesWorkspaceSidActivitiesGetResponse,
    V1WorkspacesWorkspaceSidEventsGetResponse,
    V1WorkspacesWorkspaceSidTaskChannelsGetResponse,
    V1WorkspacesWorkspaceSidTaskQueuesGetResponse,
    V1WorkspacesWorkspaceSidTaskQueuesStatisticsGetResponse,
    V1WorkspacesWorkspaceSidTasksGetResponse,
    V1WorkspacesWorkspaceSidTasksTaskSidReservationsGetResponse,
    V1WorkspacesWorkspaceSidWorkersGetResponse,
    V1WorkspacesWorkspaceSidWorkersWorkerSidChannelsGetResponse,
    V1WorkspacesWorkspaceSidWorkersWorkerSidReservationsGetResponse,
    V1WorkspacesWorkspaceSidWorkflowsGetResponse,
    WorkerReservationEnumStatus,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Taskrouter',
    version='1.42.0',
    servers=[{'url': 'https://taskrouter.twilio.com'}],
)


@app.get(
    '/v1/Workspaces',
    tags=['event_fetching'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_workspace(
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_workspace(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Workspaces/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_workspace(
    sid: constr(pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workspace(
    sid: constr(pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_workspace(
    sid: constr(pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Activities',
    tags=['workspace_management', 'activity_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_activity(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    available: Optional[str] = Query(None, alias='Available'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Activities',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_activity(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Workspaces/{WorkspaceSid}/Activities/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_activity(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WA[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Activities/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_activity(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WA[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Activities/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_activity(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WA[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/CumulativeStatistics',
    tags=['event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workspace_cumulative_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    split_by_wait_time: Optional[str] = Query(None, alias='SplitByWaitTime'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Events',
    tags=['event_fetching'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_event(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    event_type: Optional[str] = Query(None, alias='EventType'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    reservation_sid: Optional[
        constr(pattern=r'^WR[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='ReservationSid'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    task_queue_sid: Optional[
        constr(pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='TaskQueueSid'),
    task_sid: Optional[
        constr(pattern=r'^WT[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='TaskSid'),
    worker_sid: Optional[
        constr(pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='WorkerSid'),
    workflow_sid: Optional[
        constr(pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='WorkflowSid'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    sid: Optional[
        constr(pattern=r'^EV[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='Sid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Events/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_event(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^EV[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/RealTimeStatistics',
    tags=['task_channel_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workspace_real_time_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Statistics',
    tags=['event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workspace_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    split_by_wait_time: Optional[str] = Query(None, alias='SplitByWaitTime'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskChannels',
    tags=['workspace_management', 'event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_task_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/TaskChannels',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_task_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Workspaces/{WorkspaceSid}/TaskChannels/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_task_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskChannels/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/TaskChannels/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_task_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: str = Path(..., alias='Sid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues',
    tags=['workspace_management', 'worker_profile_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_task_queue(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    evaluate_worker_attributes: Optional[str] = Query(
        None, alias='EvaluateWorkerAttributes'
    ),
    worker_sid: Optional[
        constr(pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='WorkerSid'),
    ordering: Optional[str] = Query(None, alias='Ordering'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_task_queue(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues/Statistics',
    tags=['event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_task_queues_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    split_by_wait_time: Optional[str] = Query(None, alias='SplitByWaitTime'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_task_queue(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_queue(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues/{Sid}',
    tags=[
        'workspace_management',
        'activity_management',
        'task_queue_management',
        'task_channel_management',
        'event_fetching',
        'workspace_statistics',
        'task_management',
        'worker_profile_management',
        'worker_reservation_management',
        'workflow_management',
        'worker_statistics',
        'workflow_statistics',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_task_queue(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/CumulativeStatistics',
    tags=['event_fetching', 'workspace_statistics', 'task_queue_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_queue_cumulative_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_queue_sid: constr(
        pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TaskQueueSid'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    split_by_wait_time: Optional[str] = Query(None, alias='SplitByWaitTime'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/RealTimeStatistics',
    tags=['task_queue_management', 'task_channel_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_queue_real_time_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_queue_sid: constr(
        pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TaskQueueSid'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/Statistics',
    tags=['task_queue_management', 'event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_queue_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_queue_sid: constr(
        pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TaskQueueSid'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    split_by_wait_time: Optional[str] = Query(None, alias='SplitByWaitTime'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Tasks',
    tags=['workflow_management', 'task_queue_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_task(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    priority: Optional[int] = Query(None, alias='Priority'),
    assignment_status: Optional[AssignmentStatus] = Query(
        None, alias='AssignmentStatus'
    ),
    workflow_sid: Optional[
        constr(pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='WorkflowSid'),
    workflow_name: Optional[str] = Query(None, alias='WorkflowName'),
    task_queue_sid: Optional[
        constr(pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='TaskQueueSid'),
    task_queue_name: Optional[str] = Query(None, alias='TaskQueueName'),
    evaluate_task_attributes: Optional[str] = Query(
        None, alias='EvaluateTaskAttributes'
    ),
    ordering: Optional[str] = Query(None, alias='Ordering'),
    has_addons: Optional[bool] = Query(None, alias='HasAddons'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Tasks',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_task(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Workspaces/{WorkspaceSid}/Tasks/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_task(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WT[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    if__match: Optional[str] = Header(None, alias='If-Match'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Tasks/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WT[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Tasks/{Sid}',
    tags=['workspace_management', 'task_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_task(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WT[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    if__match: Optional[str] = Header(None, alias='If-Match'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Tasks/{TaskSid}/Reservations',
    tags=['worker_reservation_management', 'task_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_task_reservation(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_sid: constr(
        pattern=r'^WT[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TaskSid'),
    reservation_status: Optional[TaskReservationEnumStatus] = Query(
        None, alias='ReservationStatus'
    ),
    worker_sid: Optional[
        constr(pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='WorkerSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Tasks/{TaskSid}/Reservations/{Sid}',
    tags=['task_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_reservation(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_sid: constr(
        pattern=r'^WT[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TaskSid'),
    sid: constr(pattern=r'^WR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Tasks/{TaskSid}/Reservations/{Sid}',
    tags=['workspace_management', 'task_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_task_reservation(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_sid: constr(
        pattern=r'^WT[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='TaskSid'),
    sid: constr(pattern=r'^WR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    if__match: Optional[str] = Header(None, alias='If-Match'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers',
    tags=['activity_management', 'task_queue_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_worker(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    activity_name: Optional[str] = Query(None, alias='ActivityName'),
    activity_sid: Optional[
        constr(pattern=r'^WA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='ActivitySid'),
    available: Optional[str] = Query(None, alias='Available'),
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    target_workers_expression: Optional[str] = Query(
        None, alias='TargetWorkersExpression'
    ),
    task_queue_name: Optional[str] = Query(None, alias='TaskQueueName'),
    task_queue_sid: Optional[
        constr(pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='TaskQueueSid'),
    ordering: Optional[str] = Query(None, alias='Ordering'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Workers',
    tags=['workspace_management', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_worker(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/CumulativeStatistics',
    tags=['event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workers_cumulative_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/RealTimeStatistics',
    tags=['task_channel_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workers_real_time_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/Statistics',
    tags=['event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_worker_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    task_queue_sid: Optional[
        constr(pattern=r'^WQ[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='TaskQueueSid'),
    task_queue_name: Optional[str] = Query(None, alias='TaskQueueName'),
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_worker(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    if__match: Optional[str] = Header(None, alias='If-Match'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_worker(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_worker(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    if__match: Optional[str] = Header(None, alias='If-Match'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Channels',
    tags=['workspace_management', 'worker_profile_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_worker_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    worker_sid: constr(
        pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkerSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Channels/{Sid}',
    tags=['worker_profile_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_worker_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    worker_sid: constr(
        pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkerSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Channels/{Sid}',
    tags=['worker_profile_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_worker_channel(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    worker_sid: constr(
        pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkerSid'),
    sid: str = Path(..., alias='Sid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Reservations',
    tags=['worker_reservation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_worker_reservation(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    worker_sid: constr(
        pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkerSid'),
    reservation_status: Optional[WorkerReservationEnumStatus] = Query(
        None, alias='ReservationStatus'
    ),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Reservations/{Sid}',
    tags=['worker_profile_management', 'worker_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_worker_reservation(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    worker_sid: constr(
        pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkerSid'),
    sid: constr(pattern=r'^WR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Reservations/{Sid}',
    tags=['worker_profile_management', 'worker_reservation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_worker_reservation(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    worker_sid: constr(
        pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkerSid'),
    sid: constr(pattern=r'^WR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    if__match: Optional[str] = Header(None, alias='If-Match'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Statistics',
    tags=['event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_worker_instance_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    worker_sid: constr(
        pattern=r'^WK[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkerSid'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workflows',
    tags=['workspace_management', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_workflow(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    friendly_name: Optional[str] = Query(None, alias='FriendlyName'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Workflows',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_workflow(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Workspaces/{WorkspaceSid}/Workflows/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_workflow(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workflows/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workflow(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Workspaces/{WorkspaceSid}/Workflows/{Sid}',
    tags=['workspace_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_workflow(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    sid: constr(pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/CumulativeStatistics',
    tags=['workflow_management', 'event_fetching', 'workspace_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workflow_cumulative_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    workflow_sid: constr(
        pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkflowSid'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    split_by_wait_time: Optional[str] = Query(None, alias='SplitByWaitTime'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/RealTimeStatistics',
    tags=['task_channel_management', 'workflow_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workflow_real_time_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    workflow_sid: constr(
        pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkflowSid'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/Statistics',
    tags=['event_fetching', 'workflow_statistics'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_workflow_statistics(
    workspace_sid: constr(
        pattern=r'^WS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkspaceSid'),
    workflow_sid: constr(
        pattern=r'^WW[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='WorkflowSid'),
    minutes: Optional[int] = Query(None, alias='Minutes'),
    start_date: Optional[datetime] = Query(None, alias='StartDate'),
    end_date: Optional[datetime] = Query(None, alias='EndDate'),
    task_channel: Optional[str] = Query(None, alias='TaskChannel'),
    split_by_wait_time: Optional[str] = Query(None, alias='SplitByWaitTime'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
